# General config file

# PATHS
[paths]
questions = "utils/config/questions.toml"
llm = "utils/config/llm.toml"
# -cf to enable the following paths
output_path = "output"
schema_path = "utils/json_schema"
programs_path = "resources/sources"
exam_text_path = "resources"
sys_prompt_path = "utils/prompt/system"
usr_prompt_path = "utils/prompt/user"

# COMBINED RESULT
[combined_weights]
llm = 4.0
tests = 6.0