# General config file

# PATHS (relative to program root dir)
[paths]
questions = "src/checkmyc/config/questions.toml"
llm = "src/checkmyc/config/llm.toml"
# -cf to enable the following paths
output_path = "output"
schema_path = "src/checkmyc/data/json_schema"
programs_path = "resources/sources"
exam_text_path = "resources"
sys_prompt_path = "src/checkmyc/data/prompts/system"
usr_prompt_path = "src/checkmyc/data/prompts/user"

# COMBINED RESULT
[combined_weights]
llm = 4.0
tests = 6.0